name: ig

services:

  # ───────────────────────────────────────────
  # Backend
  # ───────────────────────────────────────────

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    environment:
      URL: http://host.docker.internal:54321/storage/v1/s3
      SUPABASE_URL: http://host.docker.internal:54321
      WATCHFILES_FORCE_POLLING: "true"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health')",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 20s

    volumes:
      # Código fuente
      - ./backend:/app

      # Entorno virtual
      - backend_venv:/opt/venv

    command: >
      sh -c "uv sync --frozen --no-dev &&
      exec uvicorn main:app --host 0.0.0.0 --port 8000 --reload"


  # ───────────────────────────────────────────
  # Frontend
  # ───────────────────────────────────────────

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev

    ports:
      - "3000:3000"

    environment:
      WATCHPACK_POLLING: "true"
      API_URL: http://backend:8000
      NEXT_PUBLIC_API_URL: http://localhost:8000
      NEXT_PUBLIC_SUPABASE_URL: http://localhost:54321
      CI: "true"

    depends_on:
      backend:
        condition: service_healthy

    volumes:
      # Código fuente
      - ./frontend:/app

      # Dependencias Node
      - frontend_node_modules:/app/node_modules

     


volumes:
  backend_venv:
  frontend_node_modules: