from typing import Protocol

from core.auth.domain.auth_email import Email


class EmailProtector(Protocol):
    def encrypt(self, email: Email) -> str: ...
    def decrypt(self, token: str) -> Email: ...
    def generate_email_hmac_identifier(self, email: Email) -> str: ...
